export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_USERINFO = 'GET_USERINFO';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const GET_USER_ADDRESS = 'GET_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';

export const CHANGE_NAV_VIEW = 'CHANGE_NAV_VIEW';
